version: "3.8"

services:
  tests:
    #Comment the following line if you uncomment the next line
    image: woudisnakes/portfolio-2023-tests:latest
    #Uncomment the following line to build the image from the Dockerfile
    #build: .
    volumes:
      - ./Portfolio-2023-RPA-tests:/app
      - ./logs:/app/logs
      - ./Portfolio-2023-RPA-tests/jsonfiles:/app/jsonfiles
    env_file: .env
    environment:
      - BROWSER=headlessfirefox
      - HOST=http://host.docker.internal:80
      - BROWSER_OPENING=${BROWSER_OPENING}
      - EMPTY_TABLE=${EMPTY_TABLE}
      - FILLED_TABLE=${FILLED_TABLE}
    command: >
      sh -c "while ! curl -s http://host.docker.internal:80 > /dev/null; do sleep 1; done &&
             rm -f /tmp/.X99-lock &&
             Xvfb :99 -screen 0 1920x1080x24 &
             sleep 10 && 
             robot --outputdir /app/logs --exclude with_no_connection Database.robot Math_Game.robot NASA_API.robot Slideshow.robot static_parts.robot && 
             pkill Xvfb"
